### PR TITLE
Gave a new look

### PR DESCRIPTION
**Pull request by Aarize29**
Change background ,added sound effect , added alot of styling.

# After
Screenshot (22)

### CODE REVIEW

**Comment by Aarize29** [comment]
Please Give hacktober  label

**Comment by Aarize29** [comment]
Give hacktober fest label please

**Comment by vaneela** [comment]
> Give hacktober fest label please

done

**Comment by Aarize29** [comment]
> > Give hacktober fest label please
> 
> done

Thanku ma'am

**Pull request merged**
