### PR TITLE
Updated CSS component to make the website responsive

### PR DESCRIPTION
**Pull request by Arcturus22**
I have added the media query to the CSS component(style.css) to make the website responsive.

### CODE REVIEW

**Comment by Arcturus22** [comment]
Screenshot-1
Screenshot-2
Screenshot-3
Screenshot-4

**Comment by vaneela** [comment]
it's nice.

**Comment by Arcturus22** [comment]
I have added the media that you asked for.
This is for Issue #4

**Comment by vaneela** [comment]
ok i'll merge it.

**Pull request merged**
